# Workflow's name
name: Build Application for Windows

# Workflow's trigger
on:
  push:


# Workflow's jobs
jobs:
  # job's id
  publish:
    # job's name
    name: Build and Publish Release
    # the type of machine to run the job on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - artifact_name: ./artifact/x64/snander.exe
            asset_name: SNANDer-Windows-64bit.exe

    if: github.event.repository.owner.id == github.event.sender.id

    # create steps
    steps:
      # step1: Check out Git Repository
      - name: Check out Git Repository
        uses: actions/checkout@v2
        with:
          ref: master

      # step2: Prepare Compilation Environment
      - name: Prepare Compilation Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get install -y pkg-config mingw-w64 tar wget make

      # step3: Build App
      - name: Build App
        run: |
          ./build-for-windows.sh

      # step4: Prepare Artifact
      - name: Prepare Artifact
        run: |
          mkdir -p ./artifact/
          cp -rf ./build/x64 ./artifact/
          tar -czvf myetc.tar.gz ./artifact/
          mkdir -p /opt/images
          sudo mv -f /home/runner/work/SNANDer/SNANDer/myetc.tar.gz /opt/images/
      - name : Upload packages
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Frp-packages
          path: /opt/images/

